addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - doxygen doc/cgv.dox

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: modern-cmake
